Repository mt-support/tribe-helpdesk, pull requests merged in 2019-05, with the labels that each got.

#35 Add basic linting of our JS | spotfix
  gulpfile.js
  package-lock.json
  package.json
Labels: merge

#39 Update build system
  .babelrc
  dist/frontend.min.js
  gulpfile.js
  package-lock.json
  package.json
Labels: merge

#40 Add local site build utilities | #124040
  README.md
  utilities/container/.dockerignore
  utilities/container/Dockerfile
  utilities/container/commands/rebuild-local-copy
  utilities/container/pause
  utilities/container/reset
  utilities/container/start
  utilities/rebuild-local-copy
  utilities/view-static-site
Labels: merge

#42 Gulp: ensure we place a copy of the new compiled assets in docs/
  gulpfile.js
  utilities/container/commands/rebuild-local-copy
  utilities/fix-docs-dir-permissions
Labels: merge

#43 Local site setup: cleanup
  gulpfile.js
  utilities/container/commands/rebuild-local-copy
  utilities/fix-docs-dir-permissions
Labels: merge

#44 Local site setup: add docs to readme
  README.md
Labels: merge

#45 Fix various aspects of gulp config | spotfix
  gulpfile.js
Labels: code review

#46 Feature/126094/login form submit button
  dist/style.min.css
  docs/style.min.css
  my-tickets.html
  package-lock.json
  scss/_components/_jumbotron.scss
  scss/_pages/_page-mytickets.scss
Labels: code review

#47 Update README to include new deploy bot command
  README.md
Labels: enhance

#48 Update background color of submit btn
  dist/style.min.css
  docs/style.min.css
  scss/_pages/_page-mytickets.scss
Labels: code review

#49 Feature/125514 change nav logo URL
  dist/frontend.min.js
  docs/frontend.min.js
  js/includes/knowledgebase.js
  js/includes/navbar.js
  kb.html
  my-tickets.html
Labels: code review

#50 Feature/127325 submit ticket sidebar
  dist/frontend.min.js
  dist/style.min.css
  docs/frontend.min.js
  docs/style.min.css
  js/includes/navbar.js
  js/includes/submitTicket.js
  scss/_pages/_all.scss
  scss/_pages/_page-submit-ticket.scss
  scss/_vendor/frontend.scss
Labels: code review, enhance

#52 Update “no results” search message
  dist/style.min.css
  docs/style.min.css
  scss/_pages/_page-search.scss
Labels: code review
