Repository mt-support/tribe-helpdesk, pull requests merged in 2019-03, with the labels that each got.

#19 Switch to JS literals and remove duplicate definitions
  .babelrc
  dist/frontend.js
  dist/frontend.min.css
  dist/frontend.min.js
  dist/scripts.min.js
  js/frontend.js
  js/injectContent.js
  js/loggedInAdvice.js
  js/loggedInFormPageAdvice.js
  js/loggedInLanderPageAdvice.js
  js/loggedOutUsersAdvice.js
  js/loginFormAdvice.js
  js/marketingAlert.js
  js/scripts.js
  package-lock.json
  package.json
Labels: code review, merge

#20 Feature/120716 helpdesk fonts
  dist/style.min.css
  scss/_base/_typography.scss
Labels: code review, merge

#22 Cleans up CSS post JS cleanup.
  dist/frontend.js
  dist/frontend.min.js
  dist/style.min.css
  index.html
  js/includes/alert.js
  js/includes/homepage.js
  scss/_base/_body.scss
  scss/_base/_buttons.scss
  scss/_base/_typography.scss
  scss/_components/_featured-content.scss
  scss/_components/_interstitial.scss
  scss/_components/_jumbotron.scss
  scss/_components/_marketing-alert.scss
  scss/_components/_navbar.scss
  scss/_components/_portals.scss
Labels: code review

#24 Feature/120455 nav updates
  dist/frontend.js
  dist/frontend.min.js
  dist/style.min.css
  js/globals/common.js
  js/includes/alert.js
  js/includes/homepage.js
  js/includes/knowledgebase.js
  js/includes/navbar.js
  js/vendor/sticky.js
  scss/_components/_category-list.scss
  scss/_components/_featured-content.scss
  scss/_components/_footer.scss
  scss/_components/_portals.scss
  scss/_pages/_page-article.scss
Labels: code review, merge

#21 Cleanup and restructure
  README.md
  dist/frontend.js
  dist/frontend.min.js
  dist/style.min.css
  gulpfile.js
  index.html
  js/frontend.js
  js/globals/common.js
  js/includes/alert.js
  js/includes/homepage.js
  js/includes/jumbotron.js
  js/includes/knowledgebase.js
  js/includes/navbar.js
  js/injectContent.js
  js/vendor/sticky.js
  scss/_base/_body.scss
  scss/_base/_buttons.scss
  scss/_base/_typography.scss
  scss/_components/_category-list.scss
  scss/_components/_featured-content.scss
  scss/_components/_footer.scss
  scss/_components/_interstitial.scss
  scss/_components/_jumbotron.scss
  scss/_components/_marketing-alert.scss
  scss/_components/_navbar.scss
  scss/_components/_portals.scss
  scss/_pages/_page-article.scss
Labels: code review

#13 Feature/120716 help desk lander
  .babelrc
  .gitignore
  README.md
  dist/frontend.js
  dist/frontend.min.js
  dist/style.min.css
  gulpfile.js
  index.html
  js/frontend.js
  js/gists.js
  js/globals/common.js
  js/includes/alert.js
  js/includes/homepage.js
  js/includes/jumbotron.js
  js/includes/knowledgebase.js
  js/includes/navbar.js
  js/knowledgebase.js
  js/vendor/gists.js
  js/vendor/sticky.js
  package-lock.json
  package.json
  scss/_base/_all.scss
  scss/_base/_body.scss
  scss/_base/_buttons.scss
  scss/_base/_links.scss
  scss/_base/_lists.scss
  scss/_base/_margin-top.scss
  scss/_base/_row.scss
  scss/_base/_typography.scss
  scss/_bits/_bits.scss
  scss/_bits/_body.scss
  scss/_bits/_buttons.scss
  scss/_bits/_links.scss
  scss/_bits/_lists.scss
  scss/_bits/_typography.scss
  scss/_components/_all.scss
  scss/_components/_category-list.scss
  scss/_components/_components.scss
  scss/_components/_featured-content.scss
  scss/_components/_footer.scss
  scss/_components/_hero.scss
  scss/_components/_interstitial.scss
  scss/_components/_jumbotron.scss
  scss/_components/_marketing-alert.scss
  scss/_components/_navbar.scss
  scss/_components/_portals.scss
  scss/_components/_section-heading.scss
  scss/_pages/_all.scss
  scss/_pages/_page-article.scss
  scss/_pages/_page-home.scss
  scss/_variables/_all.scss
  scss/_variables/_colors.scss
  scss/_variables/_media-queries.scss
  scss/_variables/_variables.scss
  scss/_vendor/frontend.scss
  scss/styles.scss
Labels: code review, merge

#25 Fixes category box container height.
  dist/style.min.css
  scss/_components/_category-list.scss
Labels: code review, merge

#26 Add missing apostrophe | spotfix
  dist/frontend.js
  dist/frontend.min.js
  js/includes/homepage.js
Labels: code review, merge

#29 Embedded gist layout fixes
  dist/frontend.js
  dist/frontend.min.js
  dist/style.min.css
  js/vendor/sticky.js
  scss/_base/_all.scss
  scss/_base/_code-blocks.scss
  scss/_base/_lists.scss
  scss/_base/_margin-top.scss
  scss/_base/_row.scss
  scss/_base/_typography.scss
  scss/_components/_all.scss
  scss/_components/_callout.scss
  scss/_components/_jumbotron.scss
  scss/_components/_marketing-alert.scss
  scss/_pages/_page-article.scss
  scss/_variables/_colors.scss
Labels: code review, question
