Repository mt-support/tribe-helpdesk, pull requests merged in 2019-04, with the labels that each got.

#31 Removing alert from support lander
  dist/frontend.js
  dist/frontend.min.js
  dist/style.min.css
  js/includes/alert.js
Labels: merge

#32 Feature/124272 Helpdesk Redesign
  dist/frontend.js
  dist/frontend.min.js
  dist/style.min.css
  gulpfile.js
  index.html
  js/includes/alert.js
  js/includes/homepage.js
  js/includes/knowledgebase.js
  scss/_base/_all.scss
  scss/_base/_body.scss
  scss/_base/_buttons.scss
  scss/_base/_code-blocks.scss
  scss/_base/_container.scss
  scss/_base/_forms.scss
  scss/_base/_links.scss
  scss/_base/_lists.scss
  scss/_base/_margin-top.scss
  scss/_base/_typography.scss
  scss/_bits/_bits.scss
  scss/_bits/_body.scss
  scss/_bits/_buttons.scss
  scss/_bits/_links.scss
  scss/_bits/_lists.scss
  scss/_bits/_typography.scss
  scss/_components/_callout.scss
  scss/_components/_category-list.scss
  scss/_components/_featured-content.scss
  scss/_components/_footer.scss
  scss/_components/_hero.scss
  scss/_components/_interstitial.scss
  scss/_components/_jumbotron.scss
  scss/_components/_marketing-alert.scss
  scss/_components/_navbar.scss
  scss/_components/_portals.scss
  scss/_pages/_all.scss
  scss/_pages/_page-article.scss
  scss/_pages/_page-category.scss
  scss/_pages/_page-mytickets.scss
  scss/_pages/_page-search.scss
  scss/_pages/page-my_profile.scss
  scss/_variables/_colors.scss
  scss/_vendor/frontend.scss
Labels: code review, merge

#33 Default to stripping the URL query | spotfix
  dist/frontend.js
  dist/frontend.min.js
  js/globals/common.js
Labels: code review, enhance, merge

#34 Fixes http instance in CSS.
  dist/style.min.css
  scss/_components/_jumbotron.scss
Labels: merge

#36 Fix/125988 header navbar fix
  dist/frontend.js
  dist/frontend.min.js
  dist/style.min.css
  images/tec-full-logo-inverted.png
  js/includes/knowledgebase.js
  js/vendor/sticky.js
  kb.html
  scss/_base/_body.scss
  scss/_components/_navbar.scss
  scss/_pages/_page-article.scss
Labels: code review

#37 Spotfix/125989/quick width fix
  dist/frontend.js
  dist/frontend.min.js
  dist/style.min.css
  js/includes/knowledgebase.js
  kb.html
  scss/_base/_body.scss
  scss/_pages/_page-article.scss
Labels: code review
