Repository mt-support/tribe-helpdesk, pull requests merged in 2019-07, with the labels that each got.

#54 Updates packages inc Lodash
  package-lock.json
  package.json
Labels: code review

#56 Feature/120139 kb tocs
  dist/frontend.min.js
  dist/style.min.css
  docs/frontend.min.js
  docs/style.min.css
  index.html
  js/globals/common.js
  js/includes/knowledgebase.js
  js/vendor/jquery.toc.min.js
  js/vendor/tocbot.js
  package-lock.json
  scss/_vendor/frontend.scss
  scss/_vendor/tocbot.scss
Labels: merge

#58 Replace tech doc URLs so we point to the new docs site | #131612
  dist/frontend.min.js
  docs/frontend.min.js
  js/includes/homepage.js
Labels: code review

#57 Tocbot CSS updates
  dist/style.min.css
  docs/style.min.css
  scss/_vendor/frontend.scss
Labels: code review, merge
